/**
  ******************************************************************************
  * @file           : main.c
  * @brief          : Main program body (STM32 Steer-by-Wire Integration Template)
  ******************************************************************************
  */

#include "main.h" // Standard HAL declarations, mapping GPIOs, etc.
#include "steering_control.h"

/* --- Private Peripherals handles --- */
ADC_HandleTypeDef hadc1;
TIM_HandleTypeDef htim1;
UART_HandleTypeDef huart2;

/* --- Steering Control Instance --- */
steering_system_t steering_sys;

/* --- Serial Buffer Variables --- */
uint8_t rx_byte = 0; // Buffer for single UART character interrupt

/* --- Prototypes --- */
void SystemClock_Config(void);
static void MX_GPIO_Init(void);
static void MX_USART2_UART_Init(void);
static void MX_ADC1_Init(void);
static void MX_TIM1_Init(void);

float Read_Steering_Feedback_Angle(void);

/**
  * @brief  The application entry point.
  * @retval int
  */
int main(void)
{
  /* Reset of all peripherals, Initializes the Flash interface and the Systick. */
  HAL_Init();

  /* Configure the system clock */
  SystemClock_Config();

  /* Initialize all configured peripherals */
  MX_GPIO_Init();
  MX_ADC1_Init();
  MX_TIM1_Init();
  MX_USART2_UART_Init();

  /* Initialize Steering Control Variables */
  steering_init(&steering_sys);

  /* Start PWM Timer Channel */
  HAL_TIM_PWM_Start(&htim1, TIM_CHANNEL_1);

  /* Start UART in Interrupt Mode to listen for Jetson commands */
  HAL_UART_Receive_IT(&huart2, &rx_byte, 1);

  uint32_t last_loop_time = HAL_GetTick();

  /* Infinite loop */
  while (1)
  {
    uint32_t current_time = HAL_GetTick();
    
    // Run at a fixed frequency of 100Hz (10ms intervals)
    if ((current_time - last_loop_time) >= 10)
    {
      float dt = (float)(current_time - last_loop_time) / 1000.0f;
      last_loop_time = current_time;
      
      // 1. Read Actual Steering Position (via ADC or Encoder)
      float actual_angle = Read_Steering_Feedback_Angle();
      steering_update_feedback(&steering_sys, actual_angle);
      
      // 2. Perform Watchdog Supervision
      steering_check_watchdog(&steering_sys, current_time);
      
      // 3. Update PID Loop Calculations
      steering_run_pid(&steering_sys, dt);
      
      // 4. Update PWM Duty Cycles and Direction Outputs
      steering_apply_output(&steering_sys);
    }
  }
}

/**
  * @brief  UART Receive Complete Callback.
  *         Triggered whenever a character is received over USART2.
  * @param  huart UART handle
  */
void HAL_UART_RxCpltCallback(UART_HandleTypeDef *huart)
{
  if (huart->Instance == USART2)
  {
    // Feed the received byte into the serial packet state machine
    steering_parse_byte(&steering_sys, rx_byte);
    
    // Re-enable interrupt for next character
    HAL_UART_Receive_IT(&huart2, &rx_byte, 1);
  }
}

/**
  * @brief  Reads steering potentiometer feedback and maps to degrees.
  * @retval Current steering angle in degrees (negative = left, positive = right).
  */
float Read_Steering_Feedback_Angle(void)
{
  HAL_ADC_Start(&hadc1);
  if (HAL_ADC_PollForConversion(&hadc1, 10) == HAL_OK)
  {
    uint32_t adc_val = HAL_ADC_GetValue(&hadc1); // Standard 12-bit ADC (0 - 4095)
    
    // Map 12-bit ADC value to degrees range [-30.0, +30.0]
    // Assuming 2048 is mechanical center (0 degrees)
    // Calibration parameters:
    float normalized = ((float)adc_val / 4095.0f); // Range 0.0 to 1.0
    float angle = (normalized - 0.5f) * 2.0f * MAX_STEERING_ANGLE_DEG;
    
    return angle;
  }
  return 0.0f; // Fallback
}

/* ============================================================================
   PERIPHERAL CONFIGURATION CODE GENERATED BY STM32CUBEMX (TEMPLATES)
   ============================================================================ */

void SystemClock_Config(void)
{
  // System Clock Configuration placeholder (e.g. 72MHz or 168MHz depending on MCU)
}

static void MX_ADC1_Init(void)
{
  // ADC1 Initialization code
}

static void MX_TIM1_Init(void)
{
  // TIM1 PWM Channel Initialization code
}

static void MX_USART2_UART_Init(void)
{
  huart2.Instance = USART2;
  huart2.Init.BaudRate = 115200;
  huart2.Init.WordLength = UART_WORDLENGTH_8B;
  huart2.Init.StopBits = UART_STOPBITS_1;
  huart2.Init.Parity = UART_PARITY_NONE;
  huart2.Init.Mode = UART_MODE_TX_RX;
  huart2.Init.HwFlowCtl = UART_HWCONTROL_NONE;
  huart2.Init.OverSampling = UART_OVERSAMPLING_16;
  HAL_UART_Init(&huart2);
}

static void MX_GPIO_Init(void)
{
  // GPIO Initialization code
}
